steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.flexible', '-t', 'gcr.io/$PROJECT_ID/expense-tracker:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/expense-tracker:latest']

images:
  - 'gcr.io/$PROJECT_ID/expense-tracker:latest' 
